computerApp/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('',  views.index, name='index'),
    path('machines/', views.machine_list_view, name='machines'),
    path('machines/<pk>', views.machine_detail_views, name='machine-detail'),
    path('add-machine',  views.machine_add_form, name='add-machine'),
    path('machines/<pk>/delete/', views.machine_delete_views, name='machine-delete'),
    path('personnes/', views.personne_list_view, name='personnes'),
    path('personnes/<pk>', views.personne_detail_views, name='personne-detail'),
    path('add-personne',  views.personne_add_form, name='add-personne'),
    path('personnes/<pk>/delete/', views.personne_delete_views, name='personne-delete'),
    path('infrastructures/', views.infrastructures, name='infrastructures'),
    path('add-infrastructure/', views.add_infrastructure, name='add-infrastructure'),
    path('infrastructures/<int:infrastructure_id>/delete/', views.delete_infrastructure, name='delete-infrastructure'),
    path('infrastructure/<int:infrastructure_id>/', views.infrastructure_details, name='infrastructure-details'),
    path('coms/', views.commu_list_view, name='coms'),
    path('coms/<pk>', views.commu_detail_views, name='com-detail'),
    path('add-com',  views.commu_add_form, name='add-com'),
    path('coms/<pk>/delete/', views.commu_delete_views, name='com-delete'),
    path('maintenances/', views.maintenance_list_views, name='maintenances'),
    path('add-maintenance', views.create_maintenance_views, name='add-maintenance'),
]

computermngt/urls.py
from django.urls import include , path
from django.contrib import admin

urlpatterns = [
    path('computerApp/', include('computerApp.urls')),
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

computerApp/models.py
from django.db import models
from datetime import datetime
from django import forms

# Create your models here.

class Machine(models.Model):
    id = models.AutoField(
        primary_key=True,
        editable=False)
        
    nom= models.CharField(
        max_length= 200
    )

    def __str__(self):
        return str(self.id) + "->" + self.nom

    def get_name(self):
        return str(self.id) + " " + self.nom

class Machine(models.Model):

    TYPE = (
        ('PC', ('PC - Run windows')),
        ('Mac', ('Mac - Run MacOS')),
        ('Serveur', ('Serveur - Simple Server to deploy virtual machines')),
        ('Switch', ('Switch - To maintains and connect servers')),
    )

    id = models.AutoField(primary_key=True, editable=False)
    nom = models.CharField(max_length=6)
    maintenanceDate = models.DateField(default=datetime.now())
    Type = models.CharField(max_length=32, choices=TYPE, default='PC')

class Personne(models.Model):
    
    id = models.AutoField(primary_key=True, editable=False)
    nom = models.CharField(max_length=6)
    prenom = models.CharField(max_length=20)

    def __str__(self):
        return str(self.id) + "->" + self.nom

    def get_name(self):
        return str(self.id) + " " + self.nom

    def get_surname(self):
        return str(self.id) + " " + self.prenom

class LoginForm(forms.Form):
    username = forms.CharField(label='Nom d\'utilisateur')
    password = forms.CharField(label='Mot de passe', widget=forms.PasswordInput)

class Infrastructure(models.Model):
    prenom = forms.CharField(required = True, label= 'Prenom')
    nom = models.CharField(max_length=200)
    machines = models.ManyToManyField(Machine)

    def __str__(self):
        return self.nom

class Commutateur(models.Model):

    id = models.AutoField(
        primary_key=True,
        editable=False)
        
    nom= models.CharField(
        max_length= 200
    )

    def __str__(self):
        return str(self.id) + "->" + self.nom

    def get_name(self):
        return str(self.id) + " " + self.nom

class Maintenance(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    date = models.DateField()
    description = models.TextField()

computerApp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from computerApp.models import Machine, Personne, Maintenance
from django.db import models

class AddMachineForm(forms.Form) : 

    nom = forms.CharField(required = True, label= 'Nom de la machine')
    type_machine = forms.ChoiceField(choices=Machine.TYPE, label='Type de machine')
    description = forms.CharField(required = True, label= 'Nom du propriétaire')

    def clean_nom(self):
        data = self.cleaned_data["nom"]
        if len(data) > 6:
            raise ValidationError(("Erreur de format pour le champ nom"))

        return data

class AddPersonneForm(forms.Form) : 
    nom = forms.CharField(required = True, label= 'Nom ')
    prenom = forms.CharField(required = True, label= 'Prenom')

    def clean_nom(self):
        data = self.cleaned_data["nom"]
        if len(data) > 6:
            raise ValidationError(("Erreur de format pour le champ nom"))

        return data       

class InfrastructureForm(forms.Form):
    nom = forms.CharField(required=True, label='Nom de l\'infrastructure')
    machines = forms.ModelMultipleChoiceField(queryset=Machine.objects.all(), widget=forms.CheckboxSelectMultiple)

class AddCommutateurForm(forms.Form) : 

    nom = forms.CharField(required = True, label= 'Nom ')

    def clean_nom(self):
        data = self.cleaned_data["nom"]
        if len(data) > 6:
            raise ValidationError(("Erreur de format pour le champ nom"))

        return data 


class MaintenanceForm(forms.ModelForm):
    class Meta:
        model = Maintenance
        fields = ('machine', 'date', 'description')

computerApp/views.py
from django.shortcuts import render, get_object_or_404, redirect 
from computerApp.models import Machine, Personne, Commutateur
from .forms import AddMachineForm, AddPersonneForm, InfrastructureForm, AddCommutateurForm, MaintenanceForm
from django.contrib.auth import authenticate, login
from .models import Infrastructure, Maintenance
from django.shortcuts import render, redirect
from django.utils import timezone
from django.core.mail import send_mail

# Create your views here.
def index(request):
    machines = Machine.objects.all()
    context = {}
    return render(request, 'index.html', context)

def machine_list_view(request):
    machines = Machine.objects.all()
    context = {'machines':machines}
    return render(request, 'computerApp/machine_list.html', context)

def machine_detail_views(request, pk):
    machine = get_object_or_404(Machine, id=pk)
    context = {'machine': machine}
    return render(request, 'computerApp/machine_detail.html', context)

def machine_add_form(request):
    if request.method == 'POST':
        form = AddMachineForm(request.POST or None)
        if form.is_valid():
            new_machine = Machine(nom=form.cleaned_data['nom'])
            new_machine.save()
            return redirect('machines')

    else:
        form = AddMachineForm()
        context = {'form' : form}
        return render(request, 'computerApp/machine_add.html', context)

def machine_delete_views(request, pk):
    machine = get_object_or_404(Machine, id=pk)
    if request.method == 'POST':
        machine.delete()
        return redirect('machines')
    context = {'machine': machine}
    return render(request, 'computerApp/machine_delete.html', context)

def personne_list_view(request):
    personnes = Personne.objects.all()
    context = {'personnes':personnes}
    return render(request, 'computerApp/personne_list.html', context)

def personne_detail_views(request, pk):
    personne = get_object_or_404(Personne, id=pk)
    context = {'personne': personne}
    return render(request, 'computerApp/personne_detail.html', context)

def personne_add_form(request):
    if request.method == 'POST':
        form = AddPersonneForm(request.POST or None)
        if form.is_valid():
            new_personne = Personne(nom=form.cleaned_data['nom'])
            new_personne.save()
            return redirect('personnes')

    else:
        form = AddPersonneForm()
        context = {'form' : form}
        return render(request, 'computerApp/personne_add.html', context)

def personne_delete_views(request, pk):
    personne = get_object_or_404(Personne, id=pk)
    if request.method == 'POST':
        personne.delete()
        return redirect('personnes')
    context = {'personne': personne}
    return render(request, 'computerApp/personne_delete.html', context)

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index.html')  # Redirige vers la page d'accueil après la connexion
        else:
            error_message = "Nom d'utilisateur ou mot de passe incorrect."
            return render(request, 'computerApp/login.html', {'error_message': error_message})
    else:
        return render(request, 'templates/computerApp/login.html')

def infrastructures(request):
    infrastructures = Infrastructure.objects.all()
    context = {'infrastructures': infrastructures}
    return render(request, 'computerApp/infrastructures.html', context)

def add_infrastructure(request):
    if request.method == 'POST':
        form = InfrastructureForm(request.POST)
        if form.is_valid():
            nom = form.cleaned_data['nom']
            machines = form.cleaned_data['machines']
            infrastructure = Infrastructure.objects.create(nom=nom)
            infrastructure.machines.set(machines)
            return redirect('infrastructures')
    else:
        form = InfrastructureForm()
    return render(request, 'computerApp/infra_add.html', {'form': form})

def delete_infrastructure(request, infrastructure_id):
    infrastructure = Infrastructure.objects.get(pk=infrastructure_id)
    infrastructure.delete()
    return redirect('infrastructures')

def infrastructure_details(request, infrastructure_id):
    infrastructure = Infrastructure.objects.get(pk=infrastructure_id)
    machines = infrastructure.machines.all()
    context = {
        'infrastructure': infrastructure,
        'machines': machines
    }
    return render(request, 'computerApp/infrastructure_details.html', context)

#Pour les commutateurs

def commu_list_view(request):
    coms = Commutateur.objects.all()
    context = {'coms':coms}
    return render(request, 'computerApp/commu_list.html', context)

def commu_detail_views(request, pk):
    com = get_object_or_404(Commutateur, id=pk)
    context = {'com': com}
    return render(request, 'computerApp/commu_detail.html', context)

def commu_add_form(request):
    if request.method == 'POST':
        form = AddCommutateurForm(request.POST or None)
        if form.is_valid():
            new_commu = Commutateur(nom=form.cleaned_data['nom'])
            new_commu.save()
            return redirect('coms')

    else:
        form = AddCommutateurForm()
        context = {'form' : form}
        return render(request, 'computerApp/commu_add.html', context)

def commu_delete_views(request, pk):
    com = get_object_or_404(Commutateur, id=pk)
    if request.method == 'POST':
        com.delete()
        return redirect('coms')
    context = {'com': com }
    return render(request, 'computerApp/commu_delete.html', context)

#Vue pour afficher la liste des entretiens et des maintenances préventives :

def maintenance_list_views(request):
    maintenances = Maintenance.objects.all()
    context = {'maintenances': maintenances}
    return render(request, 'computerApp/maintenance_list.html', context)


#Vue pour créer un nouvel entretien ou une nouvelle maintenance préventive

def create_maintenance_views(request):
    if request.method == 'POST':
        form = MaintenanceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('maintenances')
    else:
        form = MaintenanceForm()
    return render(request, 'computerApp/create_maintenance.html', {'form': form})

computerApp/templates/computerApp/commu_add.html
{% extends "index.html" %}

{% block content %}
    <h1 class="title fw-bold">Ajouter un commutateur</h1>
    <form method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.nom.id_for_label }}" class="form-label">Nom du commutateur :</label>
            {{ form.nom }}
        </div>
        <div class="form-group">
            <input type="submit" value="Créer" class="btn btn-primary">
        </div>
    </form>
{% endblock %}

computerApp/templates/computerApp/commu_detail.html
{% extends "index.html" %}

{% block content %}
    <h1 class="title fw-bold">Informations sur le commutateur</h1>
    <table class="table table-striped w-50 mx-auto col-md-12 text-center mt-4">
        <tr>
            <th>Nom : </th>
            <td>{{ com.nom }}</td>
        </tr>
        <tr>
            <th>ID : </th>
            <td>{{ com.id }}</td>
        </tr>
        <tr>
            <th>Date de maintenance : </th>
            <td>{{ com.maintenanceDate }}</td>
        </tr>
        <tr>
            <th>Type : </th>
            <td>{{ com.get_Type_display }}</td>
        </tr>
        <tr>
            <th>Propriétaire : </th>
            <td>{{ personne.nom }}</td>
        </tr>
        <tr>
            <th>Infrastructure(s) : </th>
            <td>{{ infrastructures.nom }}</td>
        </tr>
    </table>
    <div class="col-md-12 text-center mt-4">
        <img src="../../static/computerApp/images/com.png" alt="logo" class="img-fluid mx-auto" width="200" height="500">
    </div>
    <a href="{% url 'com-delete' com.id %}" class="btn btn-danger">Supprimer {{ com.nom }}</a>
    <a href="{% url 'coms' %}" class="btn btn-secondary ">Retour</a>
{% endblock %}

computerApp/templates/computerApp/commu_list.html
{% extends "index.html" %}

{% block content %}
    <h1 class="title fw-bold">Liste des Commutateurs</h1>
    {% if coms %}
        <div class="row">
            {% for com in coms %}
            <div id="PC" class="card border-info mb-3 col-md-6 col-lg-4 mx-auto" style="max-width: 18rem;"> 
                <img src="../../static/computerApp/images/com.png" class="card-img-top" alt="logo">
                <div class="card-body">
                  <h5 class="card-title">{{ com.id }} : {{ com.nom }}</h5>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="{% url 'com-detail' machine.id %}" class="btn btn-primary">Détails</a>
                </div>
            </div>
            {% endfor %}
        </div>
        <a class="btn btn-success" href="{% url 'add-com' %}" >Ajouter un commutateur</a>
    {% else %}
        <p class="tab">Il n'y a pas de commutateurs</p>
        <a class="btn btn-success" href="{% url 'add-com' %}" >Ajouter un commutateur</a>
    {% endif %}
{% endblock %}

computerApp/templates/computerApp/create_maintenance.html
{% extends "index.html" %}

{% block content %}
    <h1 class="title fw-bold">Programmer une Maintenance</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Créer" class="btn btn-primary">
    </form>
{% endblock %}

computerApp/templates/computerApp/infrastructure_details.html
{% extends "index.html" %}

{% block content %}
    <h1 class="title fw-bold">Composition de l'infrastructure : {{ infrastructure.nom }}</h1>
    {% if machines %}
        <div class="row">
            {% for machine in machines %}
            <div id="PC" class="card border-info mb-3 col-md-6 col-lg-4 mx-auto" style="max-width: 18rem;"> 
            <img src="../../static/computerApp/images/infra.png" class="card-img-top" alt="logo">
                <div class="card-body">
                    <h5 class="card-title">{{ machine.id }} : {{ machine.nom }}</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="{% url 'machine-detail' machine.id %}" class="btn btn-primary">Détails</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <p>Aucune machine n'est associée à cette infrastructure.</p>
    {% endif %}
    <div class="col-md-12 text-center mt-4">
        <img src="../../static/computerApp/images/infra.png" class="card-img-top" alt="logo">
    </div>
    <a href="#" class="btn btn-primary">Ajouter à {{ infrastructure.nom }}</a>
    <a href="{% url 'delete-infrastructure' infrastructure.id %}" class="btn btn-danger">Supprimer {{ infrastructure.nom }}</a>
    <a href="{% url 'infrastructures' %}" class="btn btn-secondary">Retour</a>
{% endblock %}

computerApp/templates/computerApp/login.html
<!-- login.html -->

{% extends "index.html" %}

{% block content %}
    <h1 class="title">Connexion</h1>
    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}
    <form method="POST" action="{% url 'index' %}" class="form">
      {% csrf_token %}
        <div class="mb-3">
          <label for="username" class="form-label">Identifiant</label>
          <input type="text" class="form-control" id="username" name="username" required>
        </div>
        <div class="mb-3">
          <label for="password" class="form-label">Mot de passe</label>
          <input type="password" class="form-control" id="password" name="password" required>
        </div>
        <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Se souvenir de moi</label>
        </div>
        <button type="submit" class="btn btn-primary">Connexion</button>
      </form>
{% endblock %}

computerApp/templates/computerApp/machine_add.html
{% extends "index.html" %}

{% block content %}
    <h1 class="title fw-bold">Ajouter une machine</h1>
    <form method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.nom.id_for_label }}" class="form-label">Nom de la machine :</label>
            {{ form.nom }}
        </div>
        <div class="form-group">
            <label for="{{ form.type_machine.id_for_label }}" class="form-label">Type de machine :</label>
            {{ form.type_machine }}
        </div>
        <div class="form-group">
            <label for="{{ form.type_machine.id_for_label }}" class="form-label">Propriétaire :</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <input type="submit" value="Créer" class="btn btn-primary">
        </div>
    </form>
{% endblock %}

computerApp/templates/computerApp/machine_delete.html
{%extends "index.html"%}

{% block content %}
  <h1 class="title">Supprimer une machine</h1>

  <p class="title">Voulez-vous vraiment supprimer la machine "{{ machine.nom }}" ?</p>

  <form method="post">
    {% csrf_token %} <!--ajoute un jeton CSRF (Cross-Site Request Forgery) au formulaire pour empêcher les attaques CSRF.-->
    <input type="submit" value="Confirmer" class="btn btn-secondary ">
    <a href="{% url 'machine-detail' machine.id %}" class="btn btn-danger ">Annuler</a>

  </form>
{% endblock %}

computerApp/templates/computerApp/machine_detail.html
{% extends "index.html" %}

{% block content %}
    <h1 class="title">Informations sur la machine</h1>
    <table class="table table-striped w-50 mx-auto col-md-12 text-center mt-4">
        <tr>
            <th>Nom : </th>
            <td>{{ machine.nom }}</td>
        </tr>
        <tr>
            <th>ID : </th>
            <td>{{ machine.id }}</td>
        </tr>
        <tr>
            <th>Date de maintenance : </th>
            <td>{{ machine.maintenanceDate }}</td>
        </tr>
        <tr>
            <th>Type : </th>
            <td>{{ machine.get_Type_display }}</td>
        </tr>
        <tr>
            <th>Propriétaire : </th>
            <td>{{ personne.nom }}</td>
        </tr>
        <tr>
            <th>Infrastructure(s) : </th>
            <td>{{ infrastructures.nom }}</td>
        </tr>
    </table>
    <div class="col-md-12 text-center mt-4">
        <img src="../../static/computerApp/images/pc.png" alt="logo" class="img-fluid mx-auto" width="200" height="500">
    </div>
    <a href="{% url 'machine-delete' machine.id %}" class="btn btn-danger">Supprimer {{ machine.nom }}</a>
    <a href="{% url 'machines' %}" class="btn btn-secondary ">Retour</a>
{% endblock %}

computerApp/templates/computerApp/machine_list.html
{% extends "index.html" %}

{% block content %}
    <h1 class="title fw-bold">Liste des machines</h1>
    {% if machines %}
        <div class="row">
            {% for machine in machines %}
            <div id="PC" class="card border-info mb-3 col-md-6 col-lg-4 mx-auto" style="max-width: 18rem;"> 
                <img src="../../static/computerApp/images/pc.png" class="card-img-top" alt="logo">
                <div class="card-body">
                  <h5 class="card-title">{{ machine.id }} : {{ machine.nom }}</h5>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="{% url 'machine-detail' machine.id %}" class="btn btn-primary">Détails</a>
                </div>
            </div>
            {% endfor %}
        </div>
        <a class="btn btn-success" href="{% url 'add-machine' %}" >Ajouter une machine</a>
    {% else %}
        <p class="tab">Il n'y a pas de machines</p>
        <a class="btn btn-success" href="{% url 'add-machine' %}" >Ajouter une machine</a>
    {% endif %}
{% endblock %}

computerApp/templates/computerApp/personne_add.html
{% extends "index.html" %}

{% block content %}
    <h1 class="title">Ajouter une personne</h1>
    <form method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.nom.id_for_label }}" class="form-label">Nom :</label>
            {{ form.nom }}
        </div>
        <div class="form-group">
            <label for="{{ form.prenom.id_for_label }}" class="form-label">Prénom :</label>
            {{ form.prenom }}
        </div>
        <div class="form-group">
            <input type="submit" value="Créer" class="btn btn-primary">
        </div>
    </form>
{% endblock %}

computerApp/templates/computerApp/personne_delete.html
{%extends "index.html"%}

{% block content %}
  <h1 class="title fw-bold">Supprimer une personne</h1>

  <p class="title">Voulez-vous vraiment supprimer "{{ personne.nom }}" ?</p>

  <form method="post">
    {% csrf_token %} <!--ajoute un jeton CSRF (Cross-Site Request Forgery) au formulaire pour empêcher les attaques CSRF.-->
    <input type="submit" value="Confirmer" class="btn btn-secondary">
    <a href="{% url 'personne-detail' personne.id %}" class="btn btn-danger">Annuler</a>

  </form>
{% endblock %}

computerApp/templates/computerApp/personne_detail.html
{% extends "index.html" %}

{% block content %}
    <h1 class="title fw-bold">Informations sur le personnel</h1>
    <table class="table table-striped w-50 mx-auto">
        <tr>
            <th>Nom : </th>
            <td>{{ personne.nom }}</td>
        </tr>
        <tr>
            <th>ID : </th>
            <td>{{ personne.id }}</td>
        </tr>
        <tr>
            <th>Date de création : </th>
            <td>{{ machine.maintenanceDate }}</td>
        </tr>
        <tr>
            <th>Fonction : </th>
            <td>{{ machine.Type }}</td>
        </tr>
        <tr>
            <th>Propriétaire : </th>
            <td>{{ personne.prenom }}</td>
        </tr>
    </table>
    <a href="{% url 'personne-delete' personne.id %}" class="btn btn-danger">Supprimer {{ personne.nom }}</a>
    <a href="{% url 'personnes' %}" class="btn btn-secondary ">Retour</a>
{% endblock %}

computerApp/templates/computerApp/personne_list.html
{% extends "index.html" %}

{% block content %}
    <h1 class="title fw-bold">Liste des personnes</h1>
    {% if personnes %}
        <div class="row">
            {% for personne in personnes %}
            <div id="PC" class="card border-info mb-3 col-md-6 col-lg-4 mx-auto" style="max-width: 18rem;"> 
                <img src="../../static/computerApp/images/user.png" class="card-img-top" alt="logo">
                <div class="card-body">
                  <h5 class="card-title">{{ personne.id }} : {{ personne.nom }} {{ personne.prenom }} </h5>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <a href="{% url 'personne-detail' personne.id %}" class="btn btn-primary">Détails</a>
                </div>
            </div>
            {% endfor %}
        </div>
        <a class="btn btn-success" href="{% url 'add-personne' %}" >Ajouter une personne</a>
    {% else %}
        <p class="tab">Il n'y a pas de machines</p>
        <a class="btn btn-success" href="{% url 'add-personne' %}" >Ajouter une personne</a>
    {% endif %}
{% endblock %}